name: Run JMeter Tests

on:
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run JMeter Test Plan
        run: |
          # Export JMeter environment in THIS step
          export JMETER_HOME=$PWD/apache-jmeter-5.6.3
          export PATH=$JMETER_HOME/bin:$PATH

          # Ensure results folder exists
          mkdir -p results

          # Run JMeter
          jmeter -n \
                 -t Satish_Jpet.jmx \
                 -l results/results.jtl \
                 -e -o results/report

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: results
